### ISSUE TITLE
PublicAnMaid and PublicMaid creation function not ideal

### ISSUE THREAD

**Issue by ustulation** [maidsafe/maidsafe_types#49]
The `PublicMaid` and `PublicAnMaid` `new()` functions require a lot of data to be passed breaking the abstraction boundary for the library user. They should simply take their private equivalents, do the rest of the stuff internally and return the newly created `Public-(Maid/AnMaid)` keys.

**Comment by mmoadeli** [comment]
Maybe one way of creating Public Id type should be by providing the private parts. This does not work when one attempts to de-serialise the type.

**Comment by ustulation** [comment]
Ah ok .. i'm not sure if i explained well. What I meant was this: If `PublicMaid` can be fully constructed on passing `Maid` then `PublicMaid` `new()` function should take only `Maid` and derive the rest of it from there. User of the library should not be made to extract Public-Keys from `Maid` and pass it to the `new()` function of `PublicMaid` etc. The serialization and de-serialization will not be affected in any way if the signature of `new()` is changed i think.

**Comment by mmoadeli** [comment]
How not? If you look at Deserialisation, it gets all fields. How do you pass it to them, where you do not have Private part?

**Comment by ustulation** [comment]
`PublicMaid::new(maid: Maid) -> PublicMaid { ... }` will be the Public constructor.
and Deserialisation does not even need a call to a member function, simply return `PublicMaid { ... }` instead of `PublicMaid::new(...)` . If at all required you can put a private function only for de-serialization but i don't think that is required. The above should do the trick.

**Comment by mmoadeli** [comment]
make sense.

On Mon, May 25, 2015 at 1:07 PM, Spandan Sharma notifications@github.com
wrote:

> PublicMaid::new(maid: Maid) -> PublicMaid { ... } will be the Public
> constructor.
> and Deserialisation does not even need a call to a member function, simply
> return PublicMaid { ... } instead of PublicMaid::new(...) . If at all
> required you can put a private function only for de-serialization but i
> don't think that is required. The above should do the trick.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/maidsafe/maidsafe_types/issues/49#issuecomment-105222641
> .

## 

Regards,
Mahmoud

maidsafe.net Limited is a limited liability company incorporated in
Scotland with number SC297540. VAT Registered 889 0608 77. Registered
Office: 72 Templehill, Troon, KA10 6BE.
Telephone Scotland: +44 1292 750020.

**Comment by mmoadeli** [comment]
done in https://github.com/maidsafe/maidsafe_types/pull/54
