### ISSUE TITLE
PublicId

### ISSUE THREAD

**Issue by ustulation** [maidsafe/maidsafe_types#50]
https://github.com/maidsafe/maidsafe_types/blob/master/src/id/public_id_type.rs#L124
still lacks proper abstraction Boundary I think. The user of this lib still has to know how to dismantle types to take out information, process them and give it back to types to create the `PublicIdType`

Infact i do find this interface counter-intuitive too:
https://github.com/maidsafe/maidsafe_types/blob/master/src/lib.rs#L60

I don't want to specify that I want to create `PublicMaid` type and then also dismantle `Maid` and give it all the information. What if I specified `PublicMaid` as type-tag and gave it `Mpid` information? So it is sub-optimal interface.

Here is what i think should be:
<1> Have Private Types (`Maid` etc)
<2> Have a trait called `PrivateType`
<3> Implement `PrivateType` for `Maid` etc. This should implement all the information you require for constructing the `PublicIdTypes`
<4> `PublicIdType` constructor should be more like:

```
new<Type: PrivateType>(private_type: Type,) {
    // extract all information including type_tag etc that you require from private_type
    // to construct your PublicIdType. I as a user should mostly see this interface and not be
    // bothered about the internals of private/public types and what type_tag is for what etc.
}
```

Then i would create it as:

```
let an_maid = AnMaid::new();
let maid = Maid::new(an_maid.clone());
let public_maid = PublicIdType::new(maid.clone());
// or PublicIdType::new(maid.clone(), an_maid.clone()) depending on what you expose as ctor.
```

So check if you think this would be better/viable/possible.

**Comment by dirvine** [comment]
Seems very reasonable Spandan, main thing si code clarity and securely creating these without being able to easily insecurely alter them. I like this approach.

**Comment by mmoadeli** [comment]
The first part is a general issue which is valid for non-id types, the type should be known to create it. 
The second part is addressed in below PR
https://github.com/maidsafe/maidsafe_types/pull/54
